version: '3.3'

services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'

  db:
    image: bitnami/mysql:8.0.26
    ports:
      - 3311:3311
    environment:
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=ecom
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PORT_NUMBER=3311
